### ISSUE TITLE
MyHTMLTestReportCN import HTMLTestRunner

### ISSUE THREAD

**Issue by NFTercel** [StrawberryFlavor/Selenium-Framework#3]
File "/Volumes/wenjian/selenium/Selenium-Framework/testsuites/TestRunner.py", line 4, in <module>
    from MyHTMLTestReportCN import HTMLTestRunner
ModuleNotFoundError: No module named 'MyHTMLTestReportCN'

**Comment by StrawberryFlavor** [comment]
HTMLTestRunner 是 Python 标准库的 unittest 模块的一个扩展，它可以生成 HTML的 测试报告。
首先要下 HTMLTestRunner.py 文件，将下载的文件放入Lib目录下，另外网上也有其他作者的修改版
